### ISSUE TITLE
Popup is entirely gray in Firefox for Android

### ISSUE THREAD

**Issue by da2x** [mikel2000/batify#27]
No visible content except for all gray background. Popup has title from /index.html.

```
BATify version: 1.0.4
Browser: Firefox 61.0
OS: Android 8.1 June 2018
Device: TA-1046 (Nokia 7 Plus)
```

**Comment by mikel2000** [comment]
Do I guess right, that this problem doesn't occur if BATify is disabled?

**Comment by da2x** [comment]
When loading extension:

```
E: Batify: ERROR: init failed: TypeError: windows is undefined. background.js:67:10
```

When opening popup:
```
W: Scripts may not close windows that were not opened by script. popup.js:29:15
E: config is undefined index.js:193
E: Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. index.js:173
```

**Comment by da2x** [comment]
This is a regression from #22 and #23. The `browser.windows` API is unavailable on Firefox for Android (there can only be one window and you can’t manipulate it – a [lightweight API variant](https://bugzilla.mozilla.org/show_bug.cgi?id=1404014) is being considered).

#22 and #23 should be reverted in favor of a solution built on `document.visibilityState` which would give much better results on desktop on all OSes and also works on mobile. See [this suggested implementation](https://github.com/usefathom/fathom/issues/70) for tracking time-on-page `onpageunload`.

**Comment by da2x** [comment]
Above comments have been updated. (Notification nudge.)

**Comment by mikel2000** [comment]
Thanks for checking this! The problem is caused by missing browser.windows API on Firefox for Android. As I don't like to create an Android specific version, I disabled now BATify for Firefox for Android. Sorry for that, I should have disabled Android initially, as I never tested it. It is enabled by default when you upload an extension.
