### ISSUE TITLE
Extension does not work with Firefox 63.0.1 

### ISSUE THREAD

**Issue by veox** [mikel2000/batify#31]
* The site list stays completely empty.
* Clicking the toolbar icon results in an empty pop-up.
* The extension's debug console is filled with messages on (what seems to me like) missing CORS permissions; as well as some other uncaught exceptions.

System: Arch Linux 64-bit.
Extension: v1.0.4

**Comment by mikel2000** [comment]
Thanks for your hint. You are right, it seems to be, that several things were changed in Firefox which leads to the problems in BATify. As only very few Firefox users installed BATify, it doesn't make sense to investigate this further. For that reason I will remove BATify now from addons.mozilla.org.
